name: ESLint check
on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Krizzu/eslint-check-action@v1.1.0
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          eslintFiles: "src"
          eslintConfig: "./eslintrc.json"
